logo: assets/images/ca979dac-76f5-42ab-a272-734ef7c8e91f.jpeg
piture: assets/images/ca979dac-76f5-42ab-a272-734ef7c8e91f.jpeg
title: Work Portfolio
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
